appenders:
  stdout_logger:
    kind: console
    encoder:
      pattern: "{h({d(%Y-%m-%d %H:%M:%S)(utc)} | {({l}):5.5} | {f}:{L} - {m}{n})}"
  file_logger:
    kind: rolling_file
    path: "log/cli.log"
    encoder: 
      pattern: "{d(%Y-%m-%d %H:%M:%S %Z)(utc)} | {({l}):5.5} | {M} | {f}:{L} - {m}{n}"
    policy:
      trigger:
        kind: size
        limit: 50kb
      roller: 
        kind: fixed_window
        base: 1
        count: 10
        pattern: "log/cli{}.log"
root:
  level: debug 
  appenders:
    - stdout_logger
    - file_logger
